from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np
import torch
from torch.utils.data import Dataset


@dataclass(frozen=True)
class LanguageExample:
    inputs: torch.Tensor
    targets: torch.Tensor
    loss_mask: torch.Tensor
    metadata: torch.Tensor


class CopyLanguageDataset(Dataset[dict[str, torch.Tensor]]):
    """A next-token language whose second half must copy a random payload."""

    def __init__(
        self,
        size: int = 10000,
        payload_length: int = 16,
        alphabet_size: int = 8,
        seed: int = 0,
    ) -> None:
        if size < 1 or payload_length < 1 or alphabet_size < 2:
            raise ValueError("size, payload_length, and alphabet_size must be valid positive values.")
        self.size = size
        self.payload_length = payload_length
        self.alphabet_size = alphabet_size
        self.seed = seed
        self.bos = alphabet_size
        self.separator = alphabet_size + 1
        self.eos = alphabet_size + 2
        self.vocab_size = alphabet_size + 3
        self.sequence_length = 2 * payload_length + 2

    def __len__(self) -> int:
        return self.size

    def __getitem__(self, index: int) -> dict[str, torch.Tensor]:
        rng = np.random.default_rng(self.seed + index)
        payload = rng.integers(0, self.alphabet_size, size=self.payload_length, dtype=np.int64)
        full = np.concatenate(
            [
                np.asarray([self.bos], dtype=np.int64),
                payload,
                np.asarray([self.separator], dtype=np.int64),
                payload,
                np.asarray([self.eos], dtype=np.int64),
            ]
        )
        inputs = full[:-1]
        targets = full[1:]
        mask = np.zeros_like(targets, dtype=np.float32)
        start = self.payload_length + 1
        stop = start + self.payload_length
        mask[start:stop] = 1.0
        return {
            "inputs": torch.from_numpy(inputs),
            "targets": torch.from_numpy(targets),
            "loss_mask": torch.from_numpy(mask),
            "metadata": torch.tensor(-1, dtype=torch.long),
        }


class RegimeGrammarDataset(Dataset[dict[str, torch.Tensor]]):
    """A symbolic next-token language generated by one of several hidden rules.

    Each regime uses a deterministic second-order modular recurrence.  A model
    must infer the active rule from context; persistent supports can then be
    tested for alignment with the hidden regime labels.
    """

    def __init__(
        self,
        size: int = 10000,
        sequence_length: int = 64,
        alphabet_size: int = 17,
        num_regimes: int = 4,
        seed: int = 0,
        switch_halfway: bool = False,
    ) -> None:
        if alphabet_size < 7:
            raise ValueError("alphabet_size should be at least seven.")
        if sequence_length < 8:
            raise ValueError("sequence_length should be at least eight.")
        if num_regimes < 2:
            raise ValueError("num_regimes should be at least two.")
        self.size = size
        self.sequence_length = sequence_length
        self.alphabet_size = alphabet_size
        self.num_regimes = num_regimes
        self.seed = seed
        self.switch_halfway = switch_halfway
        self.bos = alphabet_size
        self.vocab_size = alphabet_size + 1

        # Fixed, pairwise-distinct recurrence coefficients.
        candidate = [(1, 1, 1), (2, 1, 3), (1, 3, 2), (3, 2, 5), (4, 1, 4), (2, 5, 6)]
        if num_regimes > len(candidate):
            raise ValueError(f"num_regimes may not exceed {len(candidate)} in this reference task.")
        self.rules = candidate[:num_regimes]

    def __len__(self) -> int:
        return self.size

    def _next(self, previous: int, current: int, regime: int) -> int:
        a, b, c = self.rules[regime]
        return int((a * current + b * previous + c) % self.alphabet_size)

    def __getitem__(self, index: int) -> dict[str, torch.Tensor]:
        rng = np.random.default_rng(self.seed + index)
        first_regime = int(rng.integers(0, self.num_regimes))
        second_regime = first_regime
        if self.switch_halfway:
            choices = [r for r in range(self.num_regimes) if r != first_regime]
            second_regime = int(rng.choice(choices))

        symbols = [int(rng.integers(0, self.alphabet_size)), int(rng.integers(0, self.alphabet_size))]
        regimes = [first_regime, first_regime]
        for position in range(2, self.sequence_length + 1):
            regime = second_regime if self.switch_halfway and position >= self.sequence_length // 2 else first_regime
            symbols.append(self._next(symbols[-2], symbols[-1], regime))
            regimes.append(regime)

        full = np.asarray([self.bos] + symbols, dtype=np.int64)
        inputs = full[:-1]
        targets = full[1:]
        mask = np.ones_like(targets, dtype=np.float32)
        mask[:2] = 0.0
        metadata = np.asarray(regimes[: self.sequence_length + 1], dtype=np.int64)[: len(inputs)]
        return {
            "inputs": torch.from_numpy(inputs),
            "targets": torch.from_numpy(targets),
            "loss_mask": torch.from_numpy(mask),
            "metadata": torch.from_numpy(metadata),
        }
